sheet_path = 'samples/out/gem_collections/png'

[frames."samples/images/common/gems33"]
x = 70
y = 100
width = 4
height = 10

[frames."samples/images/common/gems24"]
x = 110
y = 100
width = 4
height = 10

[frames."samples/images/legendary/legendarygems9"]
x = 0
y = 0
width = 30
height = 30

[frames."samples/images/legendary/legendarygems12"]
x = 60
y = 30
width = 30
height = 30

[frames."samples/images/common/gems67"]
x = 248
y = 40
width = 4
height = 10

[frames."samples/images/rare/raregems5"]
x = 212
y = 30
width = 16
height = 20

[frames."samples/images/rare/raregems33"]
x = 212
y = 50
width = 16
height = 20

[frames."samples/images/legendary/legendarygems4"]
x = 150
y = 0
width = 30
height = 30

[frames."samples/images/common/gems45"]
x = 242
y = 120
width = 4
height = 10

[frames."samples/images/legendary/legendarygems7"]
x = 60
y = 0
width = 30
height = 30

[frames."samples/images/rare/raregems22"]
x = 190
y = 70
width = 16
height = 20

[frames."samples/images/rect/rect3"]
x = 16
y = 240
width = 16
height = 16

[frames."samples/images/common/gems16"]
x = 146
y = 100
width = 4
height = 10

[frames."samples/images/common/gems12"]
x = 162
y = 100
width = 4
height = 10

[frames."samples/images/common/gems32"]
x = 74
y = 100
width = 4
height = 10

[frames."samples/images/common/gems13"]
x = 158
y = 100
width = 4
height = 10

[frames."samples/images/common/gems44"]
x = 246
y = 120
width = 4
height = 10

[frames."samples/images/common/gems20"]
x = 126
y = 100
width = 4
height = 10

[frames."samples/images/common/gems22"]
x = 118
y = 100
width = 4
height = 10

[frames."samples/images/rare/raregems10"]
x = 174
y = 90
width = 16
height = 20

[frames."samples/images/common/gems41"]
x = 34
y = 100
width = 4
height = 10

[frames."samples/images/legendary/legendarygems16"]
x = 0
y = 150
width = 30
height = 30

[frames."samples/images/common/gems48"]
x = 230
y = 116
width = 4
height = 10

[frames."samples/images/common/gems57"]
x = 238
y = 100
width = 4
height = 10

[frames."samples/images/common/gems14"]
x = 154
y = 100
width = 4
height = 10

[frames."samples/images/legendary/legendarygems13"]
x = 30
y = 30
width = 30
height = 30

[frames."samples/images/common/gems70"]
x = 228
y = 30
width = 4
height = 10

[frames."samples/images/legendary/legendarygems3"]
x = 180
y = 0
width = 30
height = 30

[frames."samples/images/rare/raregems19"]
x = 30
y = 80
width = 16
height = 20

[frames."samples/images/common/gems5"]
x = 222
y = 116
width = 4
height = 10

[frames."samples/images/common/gems35"]
x = 62
y = 100
width = 4
height = 10

[frames."samples/images/rare/raregems31"]
x = 30
y = 60
width = 16
height = 20

[frames."samples/images/common/gems27"]
x = 98
y = 100
width = 4
height = 10

[frames."samples/images/common/gems25"]
x = 106
y = 100
width = 4
height = 10

[frames."samples/images/common/gems63"]
x = 252
y = 50
width = 4
height = 10

[frames."samples/images/rare/raregems17"]
x = 62
y = 80
width = 16
height = 20

[frames."samples/images/rare/raregems27"]
x = 110
y = 60
width = 16
height = 20

[frames."samples/images/common/gems34"]
x = 66
y = 100
width = 4
height = 10

[frames."samples/images/common/gems29"]
x = 90
y = 100
width = 4
height = 10

[frames."samples/images/rect/rect4"]
x = 0
y = 240
width = 16
height = 16

[frames."samples/images/rare/raregems18"]
x = 46
y = 80
width = 16
height = 20

[frames."samples/images/legendary/legendarygems18"]
x = 0
y = 90
width = 30
height = 30

[frames."samples/images/common/gems10"]
x = 170
y = 100
width = 4
height = 10

[frames."samples/images/common/gems1"]
x = 30
y = 122
width = 4
height = 10

[frames."samples/images/rare/raregems7"]
x = 180
y = 30
width = 16
height = 20

[frames."samples/images/legendary/legendarygems11"]
x = 90
y = 30
width = 30
height = 30

[frames."samples/images/rare/raregems34"]
x = 196
y = 50
width = 16
height = 20

[frames."samples/images/legendary/legendarygems20"]
x = 210
y = 0
width = 30
height = 30

[frames."samples/images/common/gems9"]
x = 174
y = 60
width = 4
height = 10

[frames."samples/images/common/gems50"]
x = 250
y = 110
width = 4
height = 10

[frames."samples/images/common/gems39"]
x = 46
y = 100
width = 4
height = 10

[frames."samples/images/common/gems8"]
x = 222
y = 70
width = 4
height = 10

[frames."samples/images/legendary/legendarygems2"]
x = 0
y = 30
width = 30
height = 30

[frames."samples/images/legendary/legendarygems1"]
x = 150
y = 30
width = 30
height = 30

[frames."samples/images/common/gems11"]
x = 166
y = 100
width = 4
height = 10

[frames."samples/images/rare/raregems23"]
x = 174
y = 70
width = 16
height = 20

[frames."samples/images/common/gems54"]
x = 250
y = 100
width = 4
height = 10

[frames."samples/images/legendary/legendarygems10"]
x = 120
y = 30
width = 30
height = 30

[frames."samples/images/common/gems47"]
x = 234
y = 116
width = 4
height = 10

[frames."samples/images/legendary/legendarygems14"]
x = 0
y = 210
width = 30
height = 30

[frames."samples/images/rare/raregems12"]
x = 142
y = 80
width = 16
height = 20

[frames."samples/images/rare/raregems25"]
x = 142
y = 60
width = 16
height = 20

[frames."samples/images/legendary/legendarygems8"]
x = 30
y = 0
width = 30
height = 30

[frames."samples/images/common/gems21"]
x = 122
y = 100
width = 4
height = 10

[frames."samples/images/common/gems36"]
x = 58
y = 100
width = 4
height = 10

[frames."samples/images/common/gems55"]
x = 246
y = 100
width = 4
height = 10

[frames."samples/images/common/gems58"]
x = 252
y = 70
width = 4
height = 10

[frames."samples/images/common/gems51"]
x = 246
y = 110
width = 4
height = 10

[frames."samples/images/common/gems66"]
x = 252
y = 40
width = 4
height = 10

[frames."samples/images/rare/raregems13"]
x = 126
y = 80
width = 16
height = 20

[frames."samples/images/rare/raregems1"]
x = 190
y = 90
width = 16
height = 20

[frames."samples/images/common/gems7"]
x = 232
y = 30
width = 4
height = 10

[frames."samples/images/common/gems69"]
x = 236
y = 30
width = 4
height = 10

[frames."samples/images/rect/rect2"]
x = 222
y = 100
width = 16
height = 16

[frames."samples/images/rect/rect2".nine_patch]
x = 4
y = 4
w = 4
h = 4

[frames."samples/images/common/gems26"]
x = 102
y = 100
width = 4
height = 10

[frames."samples/images/common/gems18"]
x = 138
y = 100
width = 4
height = 10

[frames."samples/images/common/gems4"]
x = 42
y = 100
width = 4
height = 10

[frames."samples/images/rare/raregems3"]
x = 62
y = 60
width = 16
height = 20

[frames."samples/images/rare/raregems24"]
x = 158
y = 60
width = 16
height = 20

[frames."samples/images/legendary/legendarygems6"]
x = 90
y = 0
width = 30
height = 30

[frames."samples/images/rare/raregems30"]
x = 46
y = 60
width = 16
height = 20

[frames."samples/images/rare/raregems11"]
x = 158
y = 80
width = 16
height = 20

[frames."samples/images/rare/raregems2"]
x = 238
y = 80
width = 16
height = 20

[frames."samples/images/common/gems28"]
x = 94
y = 100
width = 4
height = 10

[frames."samples/images/rare/raregems29"]
x = 78
y = 60
width = 16
height = 20

[frames."samples/images/rect/rect5"]
x = 206
y = 90
width = 16
height = 16

[frames."samples/images/rect/rect5".nine_patch]
x = 2
y = 2
w = 2
h = 2

[frames."samples/images/rare/raregems15"]
x = 94
y = 80
width = 16
height = 20

[frames."samples/images/rare/raregems26"]
x = 126
y = 60
width = 16
height = 20

[frames."samples/images/rare/raregems20"]
x = 222
y = 80
width = 16
height = 20

[frames."samples/images/common/gems6"]
x = 252
y = 60
width = 4
height = 10

[frames."samples/images/common/gems59"]
x = 248
y = 70
width = 4
height = 10

[frames."samples/images/common/gems30"]
x = 82
y = 100
width = 4
height = 10

[frames."samples/images/common/gems2"]
x = 130
y = 100
width = 4
height = 10

[frames."samples/images/common/gems31"]
x = 78
y = 100
width = 4
height = 10

[frames."samples/images/common/gems15"]
x = 150
y = 100
width = 4
height = 10

[frames."samples/images/common/gems17"]
x = 142
y = 100
width = 4
height = 10

[frames."samples/images/common/gems3"]
x = 86
y = 100
width = 4
height = 10

[frames."samples/images/common/gems37"]
x = 54
y = 100
width = 4
height = 10

[frames."samples/images/common/gems23"]
x = 114
y = 100
width = 4
height = 10

[frames."samples/images/common/gems65"]
x = 244
y = 50
width = 4
height = 10

[frames."samples/images/rare/raregems28"]
x = 94
y = 60
width = 16
height = 20

[frames."samples/images/common/gems52"]
x = 242
y = 110
width = 4
height = 10

[frames."samples/images/legendary/legendarygems5"]
x = 120
y = 0
width = 30
height = 30

[frames."samples/images/legendary/legendarygems15"]
x = 0
y = 180
width = 30
height = 30

[frames."samples/images/common/gems42"]
x = 30
y = 100
width = 4
height = 10

[frames."samples/images/rare/raregems6"]
x = 196
y = 30
width = 16
height = 20

[frames."samples/images/rare/raregems32"]
x = 228
y = 60
width = 16
height = 20

[frames."samples/images/rare/raregems9"]
x = 240
y = 0
width = 16
height = 20

[frames."samples/images/rare/raregems14"]
x = 110
y = 80
width = 16
height = 20

[frames."samples/images/rare/raregems8"]
x = 240
y = 20
width = 16
height = 20

[frames."samples/images/common/gems56"]
x = 242
y = 100
width = 4
height = 10

[frames."samples/images/common/gems49"]
x = 226
y = 116
width = 4
height = 10

[frames."samples/images/common/gems19"]
x = 134
y = 100
width = 4
height = 10

[frames."samples/images/legendary/legendarygems19"]
x = 0
y = 60
width = 30
height = 30

[frames."samples/images/common/gems46"]
x = 238
y = 120
width = 4
height = 10

[frames."samples/images/common/gems60"]
x = 248
y = 60
width = 4
height = 10

[frames."samples/images/common/gems61"]
x = 244
y = 70
width = 4
height = 10

[frames."samples/images/common/gems43"]
x = 250
y = 120
width = 4
height = 10

[frames."samples/images/rare/raregems16"]
x = 78
y = 80
width = 16
height = 20

[frames."samples/images/common/gems53"]
x = 238
y = 110
width = 4
height = 10

[frames."samples/images/common/gems62"]
x = 244
y = 60
width = 4
height = 10

[frames."samples/images/legendary/legendarygems17"]
x = 0
y = 120
width = 30
height = 30

[frames."samples/images/rare/raregems35"]
x = 180
y = 50
width = 16
height = 20

[frames."samples/images/rare/raregems21"]
x = 206
y = 70
width = 16
height = 20

[frames."samples/images/rect/rect1"]
x = 206
y = 106
width = 16
height = 16

[frames."samples/images/rect/rect1".nine_patch]
x = 2
y = 2
w = 2
h = 2

[frames."samples/images/common/gems38"]
x = 50
y = 100
width = 4
height = 10

[frames."samples/images/common/gems68"]
x = 244
y = 40
width = 4
height = 10

[frames."samples/images/rare/raregems4"]
x = 228
y = 40
width = 16
height = 20

[frames."samples/images/common/gems64"]
x = 248
y = 50
width = 4
height = 10

[frames."samples/images/common/gems40"]
x = 38
y = 100
width = 4
height = 10
