name = "gem_collections"
output_path = "out"
output_type = "Json"
template_path = ["xml-template.xml", "ratter-template.cs"]
folders = [
    "images/common",
    "images/rare",
    "images/legendary",
    "images/rect"
]

[image_options]
output_extension = "Qoi"
max_size = 4096
show_extension = false

[features]
nine_patch = true
